# backend/report.py
from fpdf import FPDF
from datetime import datetime
import os

# Install: pip install fpdf2

class DetectionReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(31, 56, 100)    # dark blue
        self.set_text_color(255, 255, 255)  # white
        self.cell(0, 12, "AI Text Detection Report", ln=True,
                  align="C", fill=True)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10,
                  f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_no()}",
                  align="C")


def generate_report(text: str, result: dict, sentences: list = None) -> bytes:
    """
    Generate a PDF report and return as bytes.

    result format:
    {
      "verdict":    "AI Generated",
      "confidence": 87.3,
      "breakdown":  { "statistical": 82, "roberta": 91, ... }
    }
    """
    pdf = DetectionReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Verdict Section ──────────────────────────────────
    verdict    = result['verdict']
    confidence = result['confidence']
    is_ai      = verdict == 'AI Generated'

    pdf.set_font("Helvetica", "B", 22)
    if is_ai:
        pdf.set_text_color(220, 53, 69)    # red
    else:
        pdf.set_text_color(40, 167, 69)    # green

    pdf.cell(0, 14, f"Verdict: {verdict}", ln=True, align="C")

    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, f"Confidence: {confidence}%", ln=True, align="C")
    pdf.ln(6)

    # ── Divider ───────────────────────────────────────────
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Score Breakdown ───────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(31, 56, 100)
    pdf.cell(0, 10, "Score Breakdown", ln=True)
    pdf.ln(2)

    breakdown = result.get('breakdown', {})
    labels    = {
        'statistical': 'Statistical (Perplexity + Burstiness)',
        'roberta':     'Transformer Classifier (RoBERTa)',
        'zero_shot':   'Zero-Shot (Log-Probability)',
        'watermark':   'Watermark Detection'
    }

    for key, label in labels.items():
        score = breakdown.get(key, 0)
        _draw_score_bar(pdf, label, score)

    pdf.ln(4)

    # ── Divider ───────────────────────────────────────────
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Submitted Text ────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(31, 56, 100)
    pdf.cell(0, 10, "Submitted Text (Preview)", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    preview = text[:800] + ("..." if len(text) > 800 else "")
    pdf.multi_cell(0, 6, preview)
    pdf.ln(4)

    # ── Sentence Analysis (if provided) ──────────────────
    if sentences:
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(31, 56, 100)
        pdf.cell(0, 10, "Sentence-Level Analysis", ln=True)
        pdf.ln(2)

        for item in sentences[:20]:  # limit to 20 sentences
            score   = item['ai_score']
            sent    = item['sentence'][:120]
            is_ai_s = item['is_ai']

            if is_ai_s:
                pdf.set_text_color(220, 53, 69)
                tag = f"[AI {score}%]"
            else:
                pdf.set_text_color(40, 167, 69)
                tag = f"[Human {100 - score}%]"

            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(30, 6, tag)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 6, sent)

    # ── Footer note ───────────────────────────────────────
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5,
        "Note: This report is generated by an AI text detection system. "
        "Results are probabilistic and should not be used as sole evidence "
        "of academic misconduct."
    )

    return bytes(pdf.output())


def _draw_score_bar(pdf, label, score):
    """Draw a labeled progress bar for a score"""
    bar_width  = 120
    bar_height = 7
    filled     = int((score / 100) * bar_width)
    x          = pdf.get_x() + 5
    y          = pdf.get_y()

    # Label
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(75, 8, label)

    # Background bar (grey)
    pdf.set_fill_color(220, 220, 220)
    pdf.rect(x + 70, y + 1, bar_width, bar_height, style='F')

    # Filled bar (color based on score)
    if score > 70:
        pdf.set_fill_color(220, 53, 69)    # red — high AI
    elif score > 40:
        pdf.set_fill_color(255, 193, 7)    # yellow — uncertain
    else:
        pdf.set_fill_color(40, 167, 69)    # green — human

    pdf.rect(x + 70, y + 1, filled, bar_height, style='F')

    # Score text
    pdf.set_text_color(60, 60, 60)
    pdf.set_xy(x + 70 + bar_width + 3, y)
    pdf.cell(20, 8, f"{score}%")
    pdf.ln(8)