import React from 'react'

export default function ScoreBreakdown({ breakdown }) {
  const models = [
    { name: 'Statistical', key: 'statistical' },
    { name: 'RoBERTa Classifier', key: 'roberta' },
    { name: 'Zero-Shot Detection', key: 'zero_shot' },
    { name: 'Watermark Detection', key: 'watermark' },
  ]

  const getBarColor = (score) => {
    if (score >= 70) return 'bg-red-500'
    if (score >= 40) return 'bg-yellow-500'
    return 'bg-green-500'
  }

  return (
    <div className="animate-slideUp bg-slate-800 rounded-xl p-6 border border-slate-700">
      <h3 className="text-xl font-bold text-white mb-6">Model Score Breakdown</h3>

      <div className="space-y-5">
        {models.map((model) => {
          const score = breakdown[model.key]
          return (
            <div key={model.key}>
              <div className="flex justify-between items-center mb-2">
                <label className="text-slate-300 font-medium">{model.name}</label>
                <span className={`font-bold text-lg ${getBarColor(score)}`}>
                  {score.toFixed(1)}%
                </span>
              </div>
              <div className="w-full bg-slate-700 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full ${getBarColor(score)} transition-all duration-700`}
                  style={{ width: `${Math.min(score, 100)}%` }}
                ></div>
              </div>
            </div>
          )
        })}
      </div>

      <div className="mt-6 p-4 bg-slate-700/50 rounded-lg border border-slate-600">
        <p className="text-slate-400 text-sm">
          <span className="font-semibold text-slate-300">How it works:</span> Our system uses multiple AI detection models
          to analyze the text. Each model focuses on different aspects of writing
          patterns to determine if the content was generated by an AI.
        </p>
      </div>
    </div>
  )
}
